name = "vitale-playground-basic-dev"
type = "javascript"
zone_id = ""
account_id = ""
route = ""
workers_dev = true

[site]
bucket = "./dist"
entry-point = "./dist/_assets/dist-worker"

[env.canary]
name = "vitale-playground-canary"

[env.production]
name = "vitale-playground-basic"

[env.rc]
name = "vitale-playground-basic-rc"
