name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: npm ci
      - run: npm run build --if-present -- --report --report-json
      - run: npm run test:unit -- --coverage
      - name: Upload report
        uses: actions/upload-artifact@v2
        with:
          name: report
          path: |
            dist/*-report.html
            dist/*-report.json
      - name: Upload coverage
        uses: actions/upload-artifact@v2
        with:
          name: coverage
          path: coverage
  
