name: Checks required

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: npm ci
      - run: npm run bootstrap
      - run: npm run build
      - run: npm run test:unit -- --coverage
      - name: Upload reports
        uses: actions/upload-artifact@v2
        with:
          name: report
          path: |
            packages/**/dist/*-report.html
            packages/**/dist/*-report.json
      - name: Upload coverages
        uses: actions/upload-artifact@v2
        with:
          name: coverages
          path: |
            packages/**/dist/*-report.html
            packages/**/dist/*-report.json
  
