name: Publish to registry

on:
  workflow_dispatch:
    inputs:
      registry:
        description: 'registry'
        default: 'npm,github'
      release-tag:
        description: 'Github tag'
      dist-tag:
        description: 'Registry dist-tag'
        default: 'latest'

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    if: contains(github.event.inputs.registry, 'npm')
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.release-tag }}
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: npm ci
      - run: npm run bootstrap
      - run: npx hygen npmrc npm --authToken ${{ secrets.NPM_PUBLISH_TOKEN }}
      - env:
          NODE_ENV: production
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
          dist-tag: ${{ github.event.inputs.dist-tag }}
        run: ./node_modules/.bin/lerna publish from-package --yes --no-verify-access

  publish-github:
    runs-on: ubuntu-latest
    if: contains(github.event.inputs.registry, 'github')
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.release-tag }}
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: npm ci
      - run: npm run bootstrap
      - run: npx hygen npmrc github --authToken ${{ secrets.GITHUB_TOKEN }}
      - env:
          NODE_ENV: production
          dist-tag: ${{ github.event.inputs.dist-tag }}
        run: ./node_modules/.bin/lerna publish from-package --yes --no-verify-access
        
