name: Publish to registry

on:
  workflow_dispatch:
    inputs:
      registry:
        description: 'registry'
        default: 'npm,github'
      release-tag:
        description: 'Github tag'
      dist-tag:
        description: 'Registry dist-tag'
        default: 'latest'

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    if: contains(github.event.inputs.registry, 'npm')
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.release-tag }}
      - uses: actions/setup-node@v1
        with:
          node-version: 14
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - run: npm run bootstrap
      - env:
          NODE_ENV: production
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
          dist-tag: ${{ github.event.inputs.dist-tag }}
        run: ./node_modules/.bin/lerna exec "npm publish --tag ${{ env.dist-tag }}" --no-bail

  publish-github:
    runs-on: ubuntu-latest
    if: contains(github.event.inputs.registry, 'github')
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.release-tag }}
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: npm ci
      - run: npm run bootstrap
      - uses: actions/setup-node@v1
        with:
          node-version: 14
          registry-url: https://npm.pkg.github.com/
          scope: thibremy
      - env:
          NODE_ENV: production
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          dist-tag: ${{ github.event.inputs.dist-tag }}
        run: ./node_modules/.bin/lerna exec "npm publish --tag ${{ env.dist-tag }}" --no-bail
        
