name: Publish to registry

on:
  workflow_dispatch:
    inputs:
      release-tag:
        description: 'Github tag'
      dist-tag:
        description: 'Registry dist-tag'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.release-tag }}
      - uses: actions/setup-node@v1
        with:
          node-version: 14
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - run: npx lerna bootstrap
      - env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
          dist-tag: ${{ github.event.inputs.release-tag }}
        run: npx lerna exec "npm publish"
        