name: Version

on: 
  workflow_dispatch:
    inputs:
      version-level:
        description: 'Version bump level major | minor | patch | premajor | preminor | prepatch | prerelease'     
        required: true
        default: 'prerelease'
      version-preid:
        required: true
        description: 'Version preid'
        default: 'rc'
jobs:
  version:
    runs-on: ubuntu-latest
    env: 
      VERSION_LEVEL: ${{ github.event.inputs.version-level }}
      VERSION_PREID: ${{ github.event.inputs.version-preid }}
    steps:
      - uses: actions/checkout@v2
      - run: |
          git config --local user.email "$(git log --format='%ae' HEAD^!)"
          git config --local user.name "$(git log --format='%an' HEAD^!)"
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: npm ci
      - name: Bump version ${{ env.VERSION_LEVEL }} --preid ${{ env.VERSION_PREID }}
        run: |
          npx lerna version ${{ env.VERSION_LEVEL }} --preid ${{ env.VERSION_PREID }} --no-push --yes 
      - run: cat lerna.json | jq '.version'
      - name: Create pull request
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: "chore(version): bump ${{ env.VERSION_LEVEL }}" 
          title: "chore(version): bump ${{ env.VERSION_LEVEL }}" 
          delete-branch: true
          branch: versions/${{ env.VERSION_PREID }}
          body: |
            Usage of `lerna version ${{ env.VERSION_LEVEL }} --preid ${{ env.VERSION_PREID }}`
